### ISSUE TITLE
OIDC Integration (OpenID) example

### ISSUE THREAD

**Issue by vsychov** [timeoff-management/timeoff-management-application#559]
Hello,

Because almost all pull requests to this repo stay ignored by maintainer for a long time, I'm creating this as issue, that may helpful for someone else. This is PoC integration oauth2-proxy, that allow to use OpenId providers (list can be found at https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider) with this app. PoC uses docker-compose, but can easy back ported to k8s or etc.

This is steps works on [current master revision](https://github.com/timeoff-management/timeoff-management-application/commit/684162c7edf9b8d6eb06a75bf849ff0383ce23c2).

1. Application build should be fixed by merging this: https://github.com/timeoff-management/timeoff-management-application/pull/531/files
2. If you want to use mysql 8+, then next patch should be applied:
```patch
Index: lib/model/db/company.js
===================================================================
diff --git a/lib/model/db/company.js b/lib/model/db/company.js
--- a/lib/model/db/company.js	(revision e0ca678927862600b65d22e090be92f608373f7f)
+++ b/lib/model/db/company.js	(date 1680865639019)
@@ -84,7 +84,7 @@
       comment      : "Indicate which mode the company account is in.",
     },
     timezone : {
-      type         : DataTypes.TEXT,
+      type         : DataTypes.STRING,
       allowNull    : true,
       defaultValue : 'Europe/London',
       comment      : 'Timezone current company is located in',

```
3. File `lib/middleware/oidc_handler.js` should be created:
```javascript
"use strict";

module.exports = async function (req, res, next) {
    const oidcEmail = req?.headers?.["x-forwarded-email"].toLowerCase();
    const oidcName = req?.headers?.["x-forwarded-user"];
    const oidcGroups = req?.headers?.["x-forwarded-groups"]; //May be used to match with DepartmentId
    const models = req.app.get('db_model');

    if (!req.user) {
        let user = await models.User.find_by_email(oidcEmail);
        if (user === null) {
            const newUser = {
                email: oidcEmail,
                lastname: oidcName,
                name: oidcName,
                companyId: 1, //TODO: move to config
                DepartmentId: 1, //TODO: map to oidcGroups
                password: "null", // it should be string, not null
                admin: false,
                auto_approve: false,
                end_date: null,
                start_date: new Date(),
            }
            await models.User.create(newUser);
            user = await models.User.find_by_email(oidcEmail);
        }
        req.user = await user.reload_with_session_details();
    }

    next();
};
```
3. `docker-compose.yaml` example for simples https://oauth2-proxy.github.io/ integration:
```yaml
version: '3.8'
services:
  app:
    build: .

  oauth2-proxy:
    image: bitnami/oauth2-proxy
    depends_on:
      - app
    ports:
      - '3000:3000'
    command:
      - oauth2-proxy
      - --upstream=http://app:3000/
      - --http-address=:3000
      - --scope=email read_api read_user openid profile
      - --cookie-secure=true
      - --provider=gitlab
      - --email-domain=*
      - --oidc-issuer-url=https://gitlab.example.com
      - --redirect-url=http://localhost:3000/oauth2/callback
       # generate cookie-secret according to https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#generating-a-cookie-secret
      - --cookie-secret=change_me
      - --client-id=change_me_to_gitlab_app_id
      - --client-secret=change_me_to_gitlab_app_secret

  db:
    image: mysql:8
    command:
      - mysqld
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_PASSWORD: 'password'
      MYSQL_USER: 'user'
      MYSQL_DATABASE: 'timeoff'
```
4. replace DB config in config/db.json, and start app, on http://localhost:3000 you should see oidc proxy login page

Hope this project will be supported again. Big thanks to authors.
